### ISSUE TITLE
Image api has CORB issue

### ISSUE THREAD

**Issue by erdahuja** [mathdroid/covid-19-api#14] opened 2020-03-14 09:48 UTC
I tried using the app and api. I wanted to add the dynamic image which is returned from this url.
`https://covid19.mathdro.id/api/og`

But this image is blocked by browser with CORB error.
can you add respective CORS policy in the api. thanks!

**Comment by mathdroid** [comment] 2020-03-14 20:10
Can you reproduce? As far as I know, this has been a non-issue since last week. Here's a screenshot from a project in Glitch: https://intelligent-fossa.glitch.me/ @erdahuja 
 
<img width="1440" alt="Screen Shot 2020-03-15 at 3 06 44 AM" src="https://user-images.githubusercontent.com/3748658/76689635-75f86100-666a-11ea-8e23-4d99c48f9c6e.png">

**Comment by mathdroid** [comment] 2020-03-16 04:36
Closing, feel free to reopen

**Closed by mathdroid** 2020-03-16 04:36 UTC
