### ISSUE TITLE
Several locations missing lat long or set to `0` when using /api/confirmed

### ISSUE THREAD

**Issue by samwiseg0** [mathdroid/covid-19-api#127] opened 2020-04-01 18:37 UTC
I am not sure if this is an issue with the source data or an issue with the API.
```json
{
"provinceState": "Georgia",
"countryRegion": "US",
"lastUpdate": 1585760736000,
"lat": null,
"long": null,
"confirmed": 1,
"recovered": 0,
"deaths": 0,
"active": 0,
"admin2": "McIntosh",
"fips": null,
"combinedKey": "McIntosh,Georgia,US",
"incidentRate": null,
"peopleTested": null,
"iso2": "US",
"iso3": "USA"
},
{
"provinceState": "Grand Princess",
"countryRegion": "US",
"lastUpdate": 1585764899000,
"lat": 0,
"long": 0,
"confirmed": 103,
"recovered": 0,
"deaths": 3,
"active": 0,
"admin2": null,
"fips": "99999",
"combinedKey": "Grand Princess, US",
"incidentRate": null,
"peopleTested": null,
"iso2": "US",
"iso3": "USA"
},
```

**Comment by k1m0ch1** [comment] 2020-04-14 07:00
right, some of the data from `JHU CSSEGISandData` return `0.0` so I think this is not a bug
![image](https://user-images.githubusercontent.com/5756522/79195307-3d5dca00-7e58-11ea-82ff-f61740e71023.png)

I'll close the issue

**Closed by k1m0ch1** 2020-04-14 07:00 UTC
