### ISSUE TITLE
Null data (0)

### ISSUE THREAD

**Issue by Sympth** [mathdroid/covid-19-api#36] opened 2020-03-18 21:18 UTC
As of right now I was making something using this api it was all working fine, but now it is returning null data (0) everything is zero.

Hopefully this gets fixed asap as this is the best api for coronavirus cases I have seen!

**Comment by k1m0ch1** [comment] 2020-04-13 18:06
duplicate of https://github.com/mathdroid/covid-19-api/issues/35

**Closed by k1m0ch1** 2020-04-13 18:06 UTC
Labels: duplicate
